# Generated by Django 4.2.11 on 2024-07-21 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_add_fuels_art_alter_add_fuels_avto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='add_fuels',
            name='time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Yaratilgan vaqts'),
        ),
    ]
